# Generated by Django 2.2.2 on 2019-06-30 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('external_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('domain_names', models.CharField(max_length=1000)),
                ('created_at', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                ('shared_tickets', models.BooleanField(default=False)),
                ('tags', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('external_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('alias', models.CharField(max_length=1000)),
                ('created_at', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('locale', models.CharField(max_length=1000)),
                ('timezone', models.CharField(max_length=1000)),
                ('last_login_at', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=1000)),
                ('signature', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
                ('suspended', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=1000)),
                ('organization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='search.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('external_id', models.CharField(max_length=1000)),
                ('created_at', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('priority', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
                ('has_incidents', models.BooleanField(default=False)),
                ('due_at', models.CharField(max_length=1000)),
                ('via', models.CharField(max_length=1000)),
                ('assignee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to='search.User')),
                ('organization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='search.Organization')),
                ('submitter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_tickets', to='search.User')),
            ],
        ),
    ]
