# Generated by Django 2.2.2 on 2019-07-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20190701_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='shared_tickets',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='has_incidents',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='shared',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='suspended',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
